name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv git zip unzip openjdk-17

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Build APK
        run: |
          buildozer init
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: qrscannerbot-apk
          path: bin/
