name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK with Buildozer
      run: |
        # Initialize buildozer if spec doesn't exist
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # Build the APK
        buildozer -v android debug
        
        # List generated files
        ls -la bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: qr-scanner-pro-apk
        path: bin/*.apk
        if-no-files-found: error
        retention-days: 7

    - name: Show build info
      run: |
        echo "Build completed!"
        echo "APK files:"
        ls -la bin/*.apk 2>/dev/null || echo "No APK files found"
